### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by Master-Hash** [Xecades/API#2]
`https://api.xecades.xyz/api?bg=fff&github=Xecades&codepen=Xecades&email=i@xecades.xyz&google=Xecades&qq=%3Cscript%3Ealert(%22xss%22)%3C/script%3E`

最简单的一个……实在不应该一点防范都没有。（

**Comment by Xecades** [comment]
> `https://api.xecades.xyz/api?bg=fff&github=Xecades&codepen=Xecades&email=i@xecades.xyz&google=Xecades&qq=%3Cscript%3Ealert(%22xss%22)%3C/script%3E`
> 
> 最简单的一个……实在不应该一点防范都没有。（

考虑了的，我觉得没必要防，这又不是什么大项目
